#ifndef MOTOR_CONFIG_H
#define MOTOR_CONFIG_H

/** Motor PWM and DRV8874 hardware limits. */
#define CHASSIS_PWM_MAX_PERMILLE              900
#define CHASSIS_PWM_DEADBAND_PERMILLE         0
#define MOTOR_DIRECTION_CHANGE_SETTLE_CYCLES  2U
#define MOTOR_REVERSE_SPEED_THRESHOLD_MPS     0.02f
#define MOTOR_REVERSE_MAX_BRAKE_CYCLES        20U
#define DRV8874_WAKE_DELAY_MS                  2U
#define DRV8874_STARTUP_STABLE_MS              5U
#define DRV8874_STARTUP_TIMEOUT_MS             50U

#endif
