#ifndef COMMUNICATION_PROTOCOL_INFO_H
#define COMMUNICATION_PROTOCOL_INFO_H

/** Upper-link protocol version exposed for diagnostics. */
#define COMMUNICATION_PROTOCOL_VERSION            3U
/** Diagnostic payload schema version exposed for diagnostics. */
#define COMMUNICATION_DIAGNOSTIC_SCHEMA_VERSION   1U
/** Fixed status payload length in bytes. */
#define COMMUNICATION_SET_VELOCITY_PAYLOAD_LENGTH 23U
#define COMMUNICATION_ESTOP_PAYLOAD_LENGTH        2U
#define COMMUNICATION_LINE_CTRL_PAYLOAD_LENGTH    2U
#define COMMUNICATION_CLEAR_FAULT_PAYLOAD_LENGTH  1U
#define COMMUNICATION_GET_INFO_PAYLOAD_LENGTH     1U
#define COMMUNICATION_HELLO_PAYLOAD_LENGTH        34U
#define COMMUNICATION_STATUS_PAYLOAD_LENGTH       92U
/** Fixed diagnostic payload length in bytes. */
#define COMMUNICATION_DIAGNOSTIC_PAYLOAD_LENGTH   28U
/** Fixed IMU status payload length and maximum payload length in bytes. */
#define COMMUNICATION_IMU_STATUS_PAYLOAD_LENGTH   99U
#define COMMUNICATION_MAX_PAYLOAD_LENGTH          99U

#define COMMUNICATION_CAPABILITY_SESSION_SEQUENCE (1UL << 0)
#define COMMUNICATION_CAPABILITY_ACK_STATUS       (1UL << 1)
#define COMMUNICATION_CAPABILITY_DIAGNOSTIC       (1UL << 2)
#define COMMUNICATION_CAPABILITY_IMU_STATUS       (1UL << 3)
#define COMMUNICATION_CAPABILITY_BUILD_IDENTITY   (1UL << 4)
#define COMMUNICATION_REQUIRED_CAPABILITIES       0x1FUL

#define COMMUNICATION_ACK_SESSION_VALID           (1U << 0)
#define COMMUNICATION_ACK_RECEIVED                (1U << 1)
#define COMMUNICATION_ACK_APPLIED                 (1U << 2)
#define COMMUNICATION_ACK_DUPLICATE               (1U << 3)
#define COMMUNICATION_ACK_REJECTED                (1U << 4)

typedef enum
{
    COMMUNICATION_REJECT_NONE = 0,
    COMMUNICATION_REJECT_MALFORMED,
    COMMUNICATION_REJECT_UNSUPPORTED_VERSION,
    COMMUNICATION_REJECT_NONFINITE,
    COMMUNICATION_REJECT_INVALID_MODE,
    COMMUNICATION_REJECT_STALE_SESSION,
    COMMUNICATION_REJECT_OUT_OF_ORDER,
    COMMUNICATION_REJECT_FAULT,
    COMMUNICATION_REJECT_SOURCE_NOT_PERMITTED
} communication_reject_reason_t;

#endif
