#ifndef ADC_MONITOR_CONFIG_H
#define ADC_MONITOR_CONFIG_H

/** ADC electrical conversion and current-quality constants. */
#define ADC_MONITOR_CHANNEL_COUNT                 5U
#define ADC_MONITOR_VREF_V                        3.3f
#define ADC_MONITOR_RESOLUTION_COUNTS             4095.0f
#define ADC_MONITOR_BATTERY_R_UPPER_OHM           47000.0f
#define ADC_MONITOR_BATTERY_R_LOWER_OHM           10000.0f
#define ADC_MONITOR_BATTERY_DIVIDER                                                                                    \
    ((ADC_MONITOR_BATTERY_R_UPPER_OHM + ADC_MONITOR_BATTERY_R_LOWER_OHM) / ADC_MONITOR_BATTERY_R_LOWER_OHM)
#define ADC_MONITOR_BATTERY_FILTER_ALPHA          0.10f
#define ADC_MONITOR_CURRENT_ZERO_SAMPLES          256U
#define ADC_MONITOR_CALIBRATION_ENABLED           1U
#define ADC_MONITOR_CURRENT_ZERO_MAX_SPAN_RAW     20U
#define ADC_MONITOR_CONTROL_MIN_WINDOW_SAMPLES    2U
#define ADC_MONITOR_CONTROL_MAX_WINDOW_SAMPLES    80U
#define ADC_MONITOR_CURRENT_SPIKE_MAX_RAW         512U

#define MOTOR_CURRENT_ZERO_V                      0.0f
#define MOTOR_CURRENT_VOLTS_PER_AMP                1.0f
#define MOTOR_CURRENT_VOLTS_PER_AMP_M1             MOTOR_CURRENT_VOLTS_PER_AMP
#define MOTOR_CURRENT_VOLTS_PER_AMP_M2             MOTOR_CURRENT_VOLTS_PER_AMP
#define MOTOR_CURRENT_VOLTS_PER_AMP_M3             MOTOR_CURRENT_VOLTS_PER_AMP
#define MOTOR_CURRENT_VOLTS_PER_AMP_M4             MOTOR_CURRENT_VOLTS_PER_AMP
#define MOTOR_CURRENT_FILTER_ALPHA                 0.25f

#endif
