#ifndef CHASSIS_LAYOUT_CONFIG_H
#define CHASSIS_LAYOUT_CONFIG_H

#include "motor_types.h"

#ifndef CHASSIS_M1_ENABLED
#define CHASSIS_M1_ENABLED 0U
#endif
#ifndef CHASSIS_M2_ENABLED
#define CHASSIS_M2_ENABLED 1U
#endif
#ifndef CHASSIS_M3_ENABLED
#define CHASSIS_M3_ENABLED 1U
#endif
#ifndef CHASSIS_M4_ENABLED
#define CHASSIS_M4_ENABLED 0U
#endif

#ifndef CHASSIS_M1_SIDE
#define CHASSIS_M1_SIDE MOTOR_SIDE_LEFT
#endif
#ifndef CHASSIS_M2_SIDE
#define CHASSIS_M2_SIDE MOTOR_SIDE_LEFT
#endif
#ifndef CHASSIS_M3_SIDE
#define CHASSIS_M3_SIDE MOTOR_SIDE_RIGHT
#endif
#ifndef CHASSIS_M4_SIDE
#define CHASSIS_M4_SIDE MOTOR_SIDE_RIGHT
#endif

#define CHASSIS_M1_MOTOR_DIR   -1
#define CHASSIS_M2_MOTOR_DIR   -1
#define CHASSIS_M3_MOTOR_DIR   1
#define CHASSIS_M4_MOTOR_DIR   1
#define CHASSIS_M1_ENCODER_DIR 1
#define CHASSIS_M2_ENCODER_DIR 1
#define CHASSIS_M3_ENCODER_DIR -1
#define CHASSIS_M4_ENCODER_DIR -1

#endif
