if(NOT DEFINED SOURCE_DIR OR NOT DEFINED BINARY_DIR OR NOT DEFINED F407_REQUESTED_BUILD_TYPE)
    message(FATAL_ERROR "SOURCE_DIR, BINARY_DIR and F407_REQUESTED_BUILD_TYPE are required")
endif()

file(STRINGS "${SOURCE_DIR}/VERSION" F407_FIRMWARE_VERSION LIMIT_COUNT 1)
execute_process(
    COMMAND git rev-parse HEAD
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE F407_GIT_SHA
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE F407_GIT_RESULT
    ERROR_QUIET
)
execute_process(
    COMMAND git status --porcelain
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE F407_GIT_STATUS
    RESULT_VARIABLE F407_STATUS_RESULT
    ERROR_QUIET
)

string(LENGTH "${F407_GIT_SHA}" F407_GIT_SHA_LENGTH)
if(NOT F407_GIT_RESULT EQUAL 0 OR NOT F407_STATUS_RESULT EQUAL 0 OR NOT F407_GIT_SHA_LENGTH EQUAL 40
   OR NOT F407_GIT_SHA MATCHES "^[0-9a-fA-F]+$")
    set(F407_GIT_SHA "unknown")
endif()

if(F407_GIT_STATUS OR F407_GIT_SHA STREQUAL "unknown")
    set(F407_BUILD_DIRTY 1)
    set(F407_BUILD_IDENTITY_VALID 0)
    set(F407_GIT_COMMIT_BYTES "0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00")
else()
    set(F407_BUILD_DIRTY 0)
    set(F407_BUILD_IDENTITY_VALID 1)
    set(F407_GIT_COMMIT_BYTES "")
    foreach(F407_GIT_BYTE_INDEX RANGE 0 19)
        math(EXPR F407_GIT_HEX_OFFSET "${F407_GIT_BYTE_INDEX} * 2")
        string(SUBSTRING "${F407_GIT_SHA}" ${F407_GIT_HEX_OFFSET} 2 F407_GIT_HEX_BYTE)
        if(F407_GIT_COMMIT_BYTES)
            string(APPEND F407_GIT_COMMIT_BYTES ", ")
        endif()
        string(APPEND F407_GIT_COMMIT_BYTES "0x${F407_GIT_HEX_BYTE}")
    endforeach()
endif()

set(F407_BUILD_TYPE "${F407_REQUESTED_BUILD_TYPE}")
file(MAKE_DIRECTORY "${BINARY_DIR}/generated")
configure_file("${SOURCE_DIR}/cmake/build_identity.h.in"
               "${BINARY_DIR}/generated/build_identity.h" @ONLY)
